### ISSUE TITLE
ロード後の画像が回転する件

### ISSUE THREAD

**Issue by ryskiod** [junprog/plant-record#4]
![Figure_1](https://user-images.githubusercontent.com/34775755/120407016-35782680-c387-11eb-9919-636576d76797.png)

直しましょう

**Comment by junprog** [comment]
* 正例だとこんな感じ
![Figure_2](https://user-images.githubusercontent.com/39183997/120408270-a91b3300-c389-11eb-8401-05989a144676.png)

* ミスはこんな感じ
![Figure_1](https://user-images.githubusercontent.com/39183997/120408280-af111400-c389-11eb-90f6-59426cf3cd6d.png)

**Comment by junprog** [comment]
解決しました
