### ISSUE TITLE
データロードの際に、resizeでground truth (mask)の情報が変わっているかも

### ISSUE THREAD

**Issue by junprog** [junprog/plant-record#6]
- 問題 

    - `tf.image.resize()` によってスケールや比率が変換し補間がはたらくことで、maskのエッジの部分で以下のような不本意な画素値がでてくる。
![Figure_1](https://user-images.githubusercontent.com/39183997/120433191-e5fd1f00-c3b5-11eb-80ad-e42c9cc08666.png)

- 解決策

    - resize から crop に変更するべき？
    - random cropにするならimageとmaskのcrop箇所をそろえる必要あり。

**Comment by junprog** [comment]
もしかしたらtfの損失関数が上手いことやってるのかも…？

**Comment by ryskiod** [comment]
表示されている画像のような学習データは使っていないけど，これはどんなデータの時になる？

**Comment by junprog** [comment]
すみません、これズームされてます。

**Comment by junprog** [comment]
ニアレストネイバー補間で解決
